version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - 31.97.205.33
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app_bridge

       